In [1]:
library(tidyverse)
library(dplyr)
library(skimr)
library(stringr)
library(magrittr)
library(oxcgrt)
library(httr)
library(rvest)

-- Attaching packages --------------------------------------- tidyverse 1.3.1 --

v ggplot2 3.3.5     v purrr   0.3.4
v tibble  3.1.5     v dplyr   1.0.7
v tidyr   1.1.4     v stringr 1.4.0
v readr   2.0.2     v forcats 0.5.1

-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()


Attaching package: 'magrittr'


The following object is masked from 'package:purrr':

    set_names


The following object is masked from 'package:tidyr':

    extract



Attaching package: 'rvest'


The following object is masked from 'package:readr':

    guess_encoding

In [2]:
#read a csv file
cases <- "https://covid19.who.int/WHO-COVID-19-global-table-data.csv"

cases_df <- read_csv(cases)

Rows: 238 Columns: 12

-- Column specification --------------------------------------------------------
Delimiter: ","
chr (2): Name, WHO Region
dbl (9): Cases - cumulative total, Cases - cumulative total per 100000 popul...


i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
#to know the structure of cases data frame
str(cases_df)

spec_tbl_df [238 x 12] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Name                                                        :

Warning message:
"One or more parsing issues, see `problems()` for details"

 chr [1:238] "Global" "United States of America" "India" "Brazil" ...
 $ WHO Region                                                  : chr [1:238] NA "Americas" "South-East Asia" "Americas" ...
 $ Cases - cumulative total                                    : num [1:238] 2.44e+08 4.53e+07 3.42e+07 2.17e+07 8.85e+06 ...
 $ Cases - cumulative total per 100000 population              : num [1:238] 3135 13673 2479 10226 13041 ...
 $ Cases - newly reported in last 7 days                       : num [1:238] 2928891 471622 106657 83650 312035 ...
 $ Cases - newly reported in last 7 days per 100000 population : num [1:238] 37.58 142.48 7.73 39.35 459.65 ...
 $ Cases - newly reported in last 24 hours                     : num [1:238] 468545 105136 13451 5797 43453 ...
 $ Deaths - cumulative total                                   : num [1:238] 4961489 732512 455653 605804 139834 ...
 $ Deaths - cumulative total per 100000 population             : num [1:238] 63.7 221.3 33 285 206 ...
 $ Deaths - newly reported in last 7 days                      : num [1:238] 48733 9668 3002 2339 982 ...
 $ Deaths - newly reported in last 7 days per 100000 population: num [1:238] 0.625 2.921 0.218 1.1 1.447 ...
 $ Deaths - newly reported in last 24 hours                    : num [1:238] 7192 1274 585 160 263 ...
 - attr(*, "spec")=
  .. cols(
  ..   Name = col_character(),
  ..   `WHO Region` = col_character(),
  ..   `Cases - cumulative total` = col_double(),
  ..   `Cases - cumulative total per 100000 population` = col_double(),
  ..   `Cases - newly reported in last 7 days` = col_double(),
  ..   `Cases - newly reported in last 7 days per 100000 population` = col_double(),
  ..   `Cases - newly reported in last 24 hours` = col_double(),
  ..   `Deaths - cumulative total` = col_double(),
  ..   `Deaths - cumulative total per 100000 population` = col_double(),
  ..   `Deaths - newly reported in last 7 days` = col_double(),
  ..   `Deaths - newly reported in last 7 days per 100000 population` = col_double(),
  ..   `Deaths - newly reported in last 24 hours` = col_number()
  .. )
 - attr(*, "problems")=<externalptr>

In [4]:
cases_df

    Name                                           WHO Region
1   Global                                         NA
2   United States of America                       Americas
3   India                                          South-East Asia
4   Brazil                                         Americas
5   The United Kingdom                             Europe
6   Russian Federation                             Europe
7   Turkey                                         Europe
8   France                                         Europe
9   Iran (Islamic Republic of)                     Eastern Mediterranean
10  Argentina                                      Americas
11  Spain                                          Europe
12  Colombia                                       Americas
13  Italy                                          Europe
14  Germany                                        Europe
15  Indonesia                                      South-East Asia
16  Mexico                                         Americas
17  Poland                                         Europe
18  South Africa                                   Africa
19  Ukraine                                        Europe
20  Philippines                                    Western Pacific
21  Malaysia                                       Western Pacific
22  Peru                                           Americas
23  Netherlands                                    Europe
24  Iraq                                           Eastern Mediterranean
25  Thailand                                       South-East Asia
26  Czechia                                        Europe
27  Japan                                          Western Pacific
28  Canada                                         Americas
29  Chile                                          Americas
30  Romania                                        Europe
... ...                                            ...
209 Cayman Islands                                 Americas
210 Anguilla                                       Americas
211 Greenland                                      Europe
212 Other                                          Other
213 Wallis and Futuna                              Western Pacific
214 Northern Mariana Islands (Commonwealth of the) Western Pacific
215 Falkland Islands (Malvinas)                    Americas
216 Montserrat                                     Americas
217 Saint Pierre and Miquelon                      Americas
218 Sint Eustatius                                 Americas
219 Holy See                                       Europe
220 Solomon Islands                                Western Pacific
221 Saba                                           Americas
222 Palau                                          Western Pacific
223 Vanuatu                                        Western Pacific
224 American Samoa                                 Western Pacific
225 Marshall Islands                               Western Pacific
226 Samoa                                          Western Pacific
227 Cook Islands                                   Western Pacific
228 Democratic People's Republic of Korea          South-East Asia
229 Kiribati                                       Western Pacific
230 Micronesia (Federated States of)               Western Pacific
231 Nauru                                          Western Pacific
232 Niue                                           Western Pacific
233 Pitcairn Islands                               Western Pacific
234 Saint Helena                                   Africa
235 Tokelau                                        Western Pacific
236 Tonga                                          Western Pacific
237 Turkmenistan                                   Europe
238 Tuvalu                                         Western Pacific
    Cases - cumulative total Cases - cumulative total per 100000 population
1   244385444                 3135.341
2    45258928                13673.283
3    34215653                 2479.387
4    21735560                10225.640
5     8853231                13041.320
6     8352601                 5723.529
7     7909111                 9377.755
8     6911563                10626.739
9     5877456                 6997.559
10    5281585                11686.015
11    5004144                10572.296
12    4992586                 9811.915
13    4747773                 7960.521
14    4506415                 5418.532
15    4241809                 1550.802
16    3784448                 2935.211
17    2990509                 7878.440
18    2920109                 4923.577
19    2825733                 6461.217
20    2765672                 2523.859
21    2442224                 7545.647
22    2196259                 6661.012
23    2093606                12026.976
24    2049240                 5094.761
25    1875315                 2686.699
26    1741859                16288.283
27    1717367                 1357.855
28    1702587                 4511.102
29    1684608                 8812.462
30    1602830                 8292.428
... ...                      ...
209 1279                     1946.135
210  859                     5725.903
211  772                     1359.825
212  764                           NA
213  454                     4036.991
214  291                      505.586
215   69                     1981.051
216   41                      820.164
217   32                      552.200
218   28                      892.004
219   26                     3213.844
220   20                        2.912
221   11                      569.064
222    8                       44.218
223    5                        1.628
224    4                        7.247
225    4                        6.757
226    1                        0.504
227    0                        0.000
228    0                        0.000
229    0                        0.000
230    0                        0.000
231    0                        0.000
232    0                        0.000
233    0                        0.000
234    0                        0.000
235    0                        0.000
236    0                        0.000
237    0                        0.000
238    0                        0.000
    Cases - newly reported in last 7 days
1   2928891
2    471622
3    106657
4     83650
5    312035
6    257776
7    194732
8     36006
9     67489
10     8122
11     8976
12    10011
13    25585
14   104784
15     4608
16    25979
17    39894
18     2854
19   146548
20    33959
21    40358
22     5863
23    38733
24    10393
25    63463
26    26305
27     2003
28    17245
29    11610
30    99408
... ...
209 184
210 161
211  84
212   0
213   0
214   2
215   0
216   0
217   0
218   0
219   0
220   0
221   0
222   0
223   2
224   1
225   0
226   0
227   0
228   0
229   0
230   0
231   0
232   0
233   0
234   0
235   0
236   0
237   0
238   0
    Cases - newly reported in last 7 days per 100000 population
1    37.57619
2   142.48300
3     7.72900
4    39.35400
5   459.64600
6   176.63800
7   230.89200
8    55.36000
9    80.35100
10   17.97100
11   18.96400
12   19.67500
13   42.89800
14  125.99300
15    1.68500
16   20.14900
17  105.10000
18    4.81200
19  335.09100
20   30.99000
21  124.69300
22   17.78200
23  222.50600
24   25.83900
25   90.92100
26  245.98000
27    1.58400
28   45.69200
29   60.73400
30  514.29900
... ...
209  279.976
210 1073.190
211  147.960
212       NA
213    0.000
214    3.475
215    0.000
216    0.000
217    0.000
218    0.000
219    0.000
220    0.000
221    0.000
222    0.000
223    0.651
224    1.812
225    0.000
226    0.000
227    0.000
228    0.000
229    0.000
230    0.000
231    0.000
232    0.000
233    0.000
234    0.000
235    0.000
236    0.000
237    0.000
238    0.000
    Cases - newly reported in last 24 hours Deaths - cumulative total
1   468545                                  4961489
2   105136                                   732512
3    13451                                   455653
4     5797                                   605804
5    43453                                   139834
6    36582                                   233898
7    29643                                    69559
8     6481                                   115168
9     9096                                   125519
10    1227                                   115851
11       0                                    87238
12    1536                                   127099
13    4053                                   131904
14   23212                                    95359
15     719                                   143299
16    1121                                   286496
17    8366                                    76672
18     331                                    88987
19   22574                                    65628
20    4393                                    42077
21    5726                                    28576
22     400                                   200083
23    5791                                    18340
24    1429                                    23024
25    8452                                    18922
26    6307                                    30667
27     263                                    18221
28    6673                                    28805
29    1157                                    37691
30   14950                                    46015
... ...                                     ...
209 83                                       2
210 66                                       1
211 26                                       0
212  0                                      13
213  0                                       7
214  0                                       3
215  0                                       0
216  0                                       1
217  0                                       0
218  0                                       0
219  0                                       0
220  0                                       0
221  0                                       0
222  0                                       0
223  2                                       0
224  0                                       0
225  0                                       0
226  0                                       0
227  0                                       0
228  0                                       0
229  0                                       0
230  0                                       0
231  0                                       0
232  0                                       0
233  0                                       0
234  0                                       0
235  0                                       0
236  0                                       0
237  0                                       0
238  0                                       0
    Deaths - cumulative total per 100000 population
1    63.65339
2   221.30100
3    33.01800
4   285.00500
5   205.98400
6   160.27600
7    82.47500
8   177.07400
9   149.44000
10  256.33100
11  184.30800
12  249.78700
13  221.16100
14  114.66000
15   52.39000
16  222.20600
17  201.99100
18  150.04000
19  150.06300
20   38.39800
21   88.29000
22  606.83000
23  105.35600
24   57.24200
25   27.10900
26  286.77000
27   14.40700
28   76.32000
29  197.16800
30  238.06400
... ...
209  3.043
210  6.666
211  0.000
212     NA
213 62.244
214  5.212
215  0.000
216 20.004
217  0.000
218  0.000
219  0.000
220  0.000
221  0.000
222  0.000
223  0.000
224  0.000
225  0.000
226  0.000
227  0.000
228  0.000
229  0.000
230  0.000
231  0.000
232  0.000
233  0.000
234  0.000
235  0.000
236  0.000
237  0.000
238  0.000
    Deaths - newly reported in last 7 days
1   48733
2    9668
3    3002
4    2339
5     982
6    7545
7    1499
8     182
9    1096
10    147
11     45
12    213
13    249
14    551
15    222
16   2019
17    418
18    313
19   3785
20   1105
21    514
22    201
23     78
24    214
25    436
26     82
27     75
28    241
29     68
30   2976
... ...
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
    Deaths - newly reported in last 7 days per 100000 population
1    0.6252197
2    2.9210000
3    0.2180000
4    1.1000000
5    1.4470000
6    5.1700000
7    1.7770000
8    0.2800000
9    1.3050000
10   0.3250000
11   0.0950000
12   0.4190000
13   0.4170000
14   0.6630000
15   0.0810000
16   1.5660000
17   1.1010000
18   0.5280000
19   8.6550000
20   1.0080000
21   1.5880000
22   0.6100000
23   0.4480000
24   0.5320000
25   0.6250000
26   0.7670000
27   0.0590000
28   0.6390000
29   0.3560000
30  15.3970000
... ...
209  0
210  0
211  0
212 NA
213  0
214  0
215  0
216  0
217  0
218  0
219  0
220  0
221  0
222  0
223  0
224  0
225  0
226  0
227  0
228  0
229  0
230  0
231  0
232  0
233  0
234  0
235  0
236  0
237  0
238  0
    Deaths - newly reported in last 24 hours
1   7192
2   1274
3    585
4    160
5    263
6   1123
7    215
8     47
9    156
10    25
11     0
12    32
13    48
14   114
15    29
16   150
17   132
18    53
19   692
20   135
21    84
22    31
23    20
24    31
25    57
26    19
27    14
28    76
29     6
30   512
... ...
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0

In [5]:
#Using the dplyr functions to manipulate the dataframe
#selected few columns, renamed and filtered
cases_df<-cases_df %>% 
    select(Name, 'Cases - cumulative total', 'Deaths - cumulative total', 'WHO Region') %>%
    rename(country_name = Name,
           region = 'WHO Region',
           total_cases = 'Cases - cumulative total',
           total_deaths = 'Deaths - cumulative total') %>%
    filter(!country_name=='Global')
cases_df

    country_name                                   total_cases total_deaths
1   United States of America                       45258928    732512
2   India                                          34215653    455653
3   Brazil                                         21735560    605804
4   The United Kingdom                              8853231    139834
5   Russian Federation                              8352601    233898
6   Turkey                                          7909111     69559
7   France                                          6911563    115168
8   Iran (Islamic Republic of)                      5877456    125519
9   Argentina                                       5281585    115851
10  Spain                                           5004144     87238
11  Colombia                                        4992586    127099
12  Italy                                           4747773    131904
13  Germany                                         4506415     95359
14  Indonesia                                       4241809    143299
15  Mexico                                          3784448    286496
16  Poland                                          2990509     76672
17  South Africa                                    2920109     88987
18  Ukraine                                         2825733     65628
19  Philippines                                     2765672     42077
20  Malaysia                                        2442224     28576
21  Peru                                            2196259    200083
22  Netherlands                                     2093606     18340
23  Iraq                                            2049240     23024
24  Thailand                                        1875315     18922
25  Czechia                                         1741859     30667
26  Japan                                           1717367     18221
27  Canada                                          1702587     28805
28  Chile                                           1684608     37691
29  Romania                                         1602830     46015
30  Bangladesh                                      1568563     27841
... ...                                            ...         ...
208 Cayman Islands                                 1279         2
209 Anguilla                                        859         1
210 Greenland                                       772         0
211 Other                                           764        13
212 Wallis and Futuna                               454         7
213 Northern Mariana Islands (Commonwealth of the)  291         3
214 Falkland Islands (Malvinas)                      69         0
215 Montserrat                                       41         1
216 Saint Pierre and Miquelon                        32         0
217 Sint Eustatius                                   28         0
218 Holy See                                         26         0
219 Solomon Islands                                  20         0
220 Saba                                             11         0
221 Palau                                             8         0
222 Vanuatu                                           5         0
223 American Samoa                                    4         0
224 Marshall Islands                                  4         0
225 Samoa                                             1         0
226 Cook Islands                                      0         0
227 Democratic People's Republic of Korea             0         0
228 Kiribati                                          0         0
229 Micronesia (Federated States of)                  0         0
230 Nauru                                             0         0
231 Niue                                              0         0
232 Pitcairn Islands                                  0         0
233 Saint Helena                                      0         0
234 Tokelau                                           0         0
235 Tonga                                             0         0
236 Turkmenistan                                      0         0
237 Tuvalu                                            0         0
    region
1   Americas
2   South-East Asia
3   Americas
4   Europe
5   Europe
6   Europe
7   Europe
8   Eastern Mediterranean
9   Americas
10  Europe
11  Americas
12  Europe
13  Europe
14  South-East Asia
15  Americas
16  Europe
17  Africa
18  Europe
19  Western Pacific
20  Western Pacific
21  Americas
22  Europe
23  Eastern Mediterranean
24  South-East Asia
25  Europe
26  Western Pacific
27  Americas
28  Americas
29  Europe
30  South-East Asia
... ...
208 Americas
209 Americas
210 Europe
211 Other
212 Western Pacific
213 Western Pacific
214 Americas
215 Americas
216 Americas
217 Americas
218 Europe
219 Western Pacific
220 Americas
221 Western Pacific
222 Western Pacific
223 Western Pacific
224 Western Pacific
225 Western Pacific
226 Western Pacific
227 South-East Asia
228 Western Pacific
229 Western Pacific
230 Western Pacific
231 Western Pacific
232 Western Pacific
233 Africa
234 Western Pacific
235 Western Pacific
236 Europe
237 Western Pacific

In [6]:
#used for country codes
library(countrycode)

In [7]:
#iso 3 character code for the country name
country_code <- countrycode(cases_df$country_name, 'country.name', 'iso3c')

Warning message in countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest, :
"Some values were not matched unambiguously: Bonaire, Kosovo[1], Other, Saba, Saint Martin, Sint Eustatius
"

In [8]:
#adding a new column country code by matching the country name
cases_df <- cases_df %>%
    add_column(country_code = if_else(.$country_name == countrycode(cases_df$country_name, 'country.name', 'iso3c'), country_code, country_code),
              .before="country_name")

Warning message in countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest, :
"Some values were not matched unambiguously: Bonaire, Kosovo[1], Other, Saba, Saint Martin, Sint Eustatius
"

In [9]:
#to combine three rows with same country code
country = c("Bonaire", "Saba", "Sint Eustatius")
c <- cases_df %>% filter(country_name %in% country) %>%
     summarize_if(is.numeric, sum, na.rm=TRUE) %>%
     mutate(country_name = "Bonaire,Saba,Sint Eustatius")

In [10]:
country_bes<- c %>% select(country_name, total_cases, total_deaths)

In [11]:
country_bes

  country_name                total_cases total_deaths
1 Bonaire,Saba,Sint Eustatius 2390        19

In [12]:
#drops three rows
cases_df <- cases_df[!(cases_df$country_name == "Bonaire" |
                       cases_df$country_name ==  "Saba" |
                       cases_df$country_name ==  "Sint Eustatius"),]

In [13]:
cases <- cases_df %>%
    filter(country_name == 'Bonaire,Sint Eustatius,Saba') %>%
    mutate(country_code = "BES")

In [14]:
cases_df<-cases_df[!(cases_df$country_name=="Other"),]

In [15]:
cases_df

    country_code country_name                                   total_cases
1   USA          United States of America                       45258928
2   IND          India                                          34215653
3   BRA          Brazil                                         21735560
4   GBR          The United Kingdom                              8853231
5   RUS          Russian Federation                              8352601
6   TUR          Turkey                                          7909111
7   FRA          France                                          6911563
8   IRN          Iran (Islamic Republic of)                      5877456
9   ARG          Argentina                                       5281585
10  ESP          Spain                                           5004144
11  COL          Colombia                                        4992586
12  ITA          Italy                                           4747773
13  DEU          Germany                                         4506415
14  IDN          Indonesia                                       4241809
15  MEX          Mexico                                          3784448
16  POL          Poland                                          2990509
17  ZAF          South Africa                                    2920109
18  UKR          Ukraine                                         2825733
19  PHL          Philippines                                     2765672
20  MYS          Malaysia                                        2442224
21  PER          Peru                                            2196259
22  NLD          Netherlands                                     2093606
23  IRQ          Iraq                                            2049240
24  THA          Thailand                                        1875315
25  CZE          Czechia                                         1741859
26  JPN          Japan                                           1717367
27  CAN          Canada                                          1702587
28  CHL          Chile                                           1684608
29  ROU          Romania                                         1602830
30  BGD          Bangladesh                                      1568563
... ...          ...                                            ...
204 GGY          Guernsey                                       2055
205 FRO          Faroe Islands                                  1778
206 BLM          Saint Barth\351lemy                               1659
207 CYM          Cayman Islands                                 1279
208 AIA          Anguilla                                        859
209 GRL          Greenland                                       772
210 WLF          Wallis and Futuna                               454
211 MNP          Northern Mariana Islands (Commonwealth of the)  291
212 FLK          Falkland Islands (Malvinas)                      69
213 MSR          Montserrat                                       41
214 SPM          Saint Pierre and Miquelon                        32
215 VAT          Holy See                                         26
216 SLB          Solomon Islands                                  20
217 PLW          Palau                                             8
218 VUT          Vanuatu                                           5
219 ASM          American Samoa                                    4
220 MHL          Marshall Islands                                  4
221 WSM          Samoa                                             1
222 COK          Cook Islands                                      0
223 PRK          Democratic People's Republic of Korea             0
224 KIR          Kiribati                                          0
225 FSM          Micronesia (Federated States of)                  0
226 NRU          Nauru                                             0
227 NIU          Niue                                              0
228 PCN          Pitcairn Islands                                  0
229 SHN          Saint Helena                                      0
230 TKL          Tokelau                                           0
231 TON          Tonga                                             0
232 TKM          Turkmenistan                                      0
233 TUV          Tuvalu                                            0
    total_deaths region
1   732512       Americas
2   455653       South-East Asia
3   605804       Americas
4   139834       Europe
5   233898       Europe
6    69559       Europe
7   115168       Europe
8   125519       Eastern Mediterranean
9   115851       Americas
10   87238       Europe
11  127099       Americas
12  131904       Europe
13   95359       Europe
14  143299       South-East Asia
15  286496       Americas
16   76672       Europe
17   88987       Africa
18   65628       Europe
19   42077       Western Pacific
20   28576       Western Pacific
21  200083       Americas
22   18340       Europe
23   23024       Eastern Mediterranean
24   18922       South-East Asia
25   30667       Europe
26   18221       Western Pacific
27   28805       Americas
28   37691       Americas
29   46015       Europe
30   27841       South-East Asia
... ...          ...
204 22           Europe
205  2           Europe
206  4           Americas
207  2           Americas
208  1           Americas
209  0           Europe
210  7           Western Pacific
211  3           Western Pacific
212  0           Americas
213  1           Americas
214  0           Americas
215  0           Europe
216  0           Western Pacific
217  0           Western Pacific
218  0           Western Pacific
219  0           Western Pacific
220  0           Western Pacific
221  0           Western Pacific
222  0           Western Pacific
223  0           South-East Asia
224  0           Western Pacific
225  0           Western Pacific
226  0           Western Pacific
227  0           Western Pacific
228  0           Western Pacific
229  0           Africa
230  0           Western Pacific
231  0           Western Pacific
232  0           Europe
233  0           Western Pacific

In [16]:
#changing the country name; old name to new name
cases_df$country_name[cases_df$contry_name == "Saint Martin"] <- 'Sint Maarten'

Warning message:
"Unknown or uninitialised column: `contry_name`."

In [17]:
cases_df<-cases_df [(!(cases_df$country_name=="Saint Martin") & !(cases_df$country_name=="Kosovo[1]")),]

In [18]:
cases_df

    country_code country_name                                   total_cases
1   USA          United States of America                       45258928
2   IND          India                                          34215653
3   BRA          Brazil                                         21735560
4   GBR          The United Kingdom                              8853231
5   RUS          Russian Federation                              8352601
6   TUR          Turkey                                          7909111
7   FRA          France                                          6911563
8   IRN          Iran (Islamic Republic of)                      5877456
9   ARG          Argentina                                       5281585
10  ESP          Spain                                           5004144
11  COL          Colombia                                        4992586
12  ITA          Italy                                           4747773
13  DEU          Germany                                         4506415
14  IDN          Indonesia                                       4241809
15  MEX          Mexico                                          3784448
16  POL          Poland                                          2990509
17  ZAF          South Africa                                    2920109
18  UKR          Ukraine                                         2825733
19  PHL          Philippines                                     2765672
20  MYS          Malaysia                                        2442224
21  PER          Peru                                            2196259
22  NLD          Netherlands                                     2093606
23  IRQ          Iraq                                            2049240
24  THA          Thailand                                        1875315
25  CZE          Czechia                                         1741859
26  JPN          Japan                                           1717367
27  CAN          Canada                                          1702587
28  CHL          Chile                                           1684608
29  ROU          Romania                                         1602830
30  BGD          Bangladesh                                      1568563
... ...          ...                                            ...
202 GGY          Guernsey                                       2055
203 FRO          Faroe Islands                                  1778
204 BLM          Saint Barth\351lemy                               1659
205 CYM          Cayman Islands                                 1279
206 AIA          Anguilla                                        859
207 GRL          Greenland                                       772
208 WLF          Wallis and Futuna                               454
209 MNP          Northern Mariana Islands (Commonwealth of the)  291
210 FLK          Falkland Islands (Malvinas)                      69
211 MSR          Montserrat                                       41
212 SPM          Saint Pierre and Miquelon                        32
213 VAT          Holy See                                         26
214 SLB          Solomon Islands                                  20
215 PLW          Palau                                             8
216 VUT          Vanuatu                                           5
217 ASM          American Samoa                                    4
218 MHL          Marshall Islands                                  4
219 WSM          Samoa                                             1
220 COK          Cook Islands                                      0
221 PRK          Democratic People's Republic of Korea             0
222 KIR          Kiribati                                          0
223 FSM          Micronesia (Federated States of)                  0
224 NRU          Nauru                                             0
225 NIU          Niue                                              0
226 PCN          Pitcairn Islands                                  0
227 SHN          Saint Helena                                      0
228 TKL          Tokelau                                           0
229 TON          Tonga                                             0
230 TKM          Turkmenistan                                      0
231 TUV          Tuvalu                                            0
    total_deaths region
1   732512       Americas
2   455653       South-East Asia
3   605804       Americas
4   139834       Europe
5   233898       Europe
6    69559       Europe
7   115168       Europe
8   125519       Eastern Mediterranean
9   115851       Americas
10   87238       Europe
11  127099       Americas
12  131904       Europe
13   95359       Europe
14  143299       South-East Asia
15  286496       Americas
16   76672       Europe
17   88987       Africa
18   65628       Europe
19   42077       Western Pacific
20   28576       Western Pacific
21  200083       Americas
22   18340       Europe
23   23024       Eastern Mediterranean
24   18922       South-East Asia
25   30667       Europe
26   18221       Western Pacific
27   28805       Americas
28   37691       Americas
29   46015       Europe
30   27841       South-East Asia
... ...          ...
202 22           Europe
203  2           Europe
204  4           Americas
205  2           Americas
206  1           Americas
207  0           Europe
208  7           Western Pacific
209  3           Western Pacific
210  0           Americas
211  1           Americas
212  0           Americas
213  0           Europe
214  0           Western Pacific
215  0           Western Pacific
216  0           Western Pacific
217  0           Western Pacific
218  0           Western Pacific
219  0           Western Pacific
220  0           Western Pacific
221  0           South-East Asia
222  0           Western Pacific
223  0           Western Pacific
224  0           Western Pacific
225  0           Western Pacific
226  0           Western Pacific
227  0           Africa
228  0           Western Pacific
229  0           Western Pacific
230  0           Europe
231  0           Western Pacific

In [19]:
#to collect the vaccine data
url_vaccines <- "https://covid19.who.int/who-data/vaccination-data.csv"

vaccines_df <- read_csv(url_vaccines)

Rows: 228 Columns: 14

-- Column specification --------------------------------------------------------
Delimiter: ","
chr  (5): COUNTRY, ISO3, WHO_REGION, DATA_SOURCE, VACCINES_USED
dbl  (7): TOTAL_VACCINATIONS, PERSONS_VACCINATED_1PLUS_DOSE, TOTAL_VACCINATI...
date (2): DATE_UPDATED, FIRST_VACCINE_DATE


i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [20]:
head(vaccines_df)

  COUNTRY                     ISO3 WHO_REGION DATA_SOURCE DATE_UPDATED
1 Falkland Islands (Malvinas) FLK  AMRO       OWID        2021-04-14
2 Saint Helena                SHN  AFRO       OWID        2021-05-05
3 Jersey                      JEY  EURO       OWID        2021-10-18
4 Liechtenstein               LIE  OTHER      OWID        2021-10-21
5 Guernsey                    GGY  EURO       OWID        2021-10-18
6 Isle of Man                 IMN  EURO       OWID        2021-10-21
  TOTAL_VACCINATIONS PERSONS_VACCINATED_1PLUS_DOSE TOTAL_VACCINATIONS_PER100
1   4407              2632                         126.529
2   7892              4361                         129.995
3 162928             78261                         151.145
4  48245             24829                         124.513
5 102548                NA                         159.068
6 131628             67353                         154.798
  PERSONS_VACCINATED_1PLUS_DOSE_PER100 PERSONS_FULLY_VACCINATED
1 75.567                                1775
2 71.833                                3531
3 72.601                               74327
4 64.080                               24124
5     NA                                  NA
6 79.209                               64275
  PERSONS_FULLY_VACCINATED_PER100
1 50.962
2 58.162
3 68.952
4 62.260
5     NA
6 75.589
  VACCINES_USED
1 AstraZeneca - AZD1222
2 AstraZeneca - AZD1222
3 Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty
4 Moderna - mRNA-1273, Pfizer BioNTech - Comirnaty
5 Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty
6 Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty
  FIRST_VACCINE_DATE NUMBER_VACCINES_TYPES_USED
1 <NA>               1
2 <NA>               1
3 <NA>               3
4 <NA>               2
5 <NA>               3
6 <NA>               3

In [21]:
str(vaccines_df)

spec_tbl_df [228 x 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ COUNTRY                             : chr [1:228] "Falkland Islands (Malvinas)" "Saint Helena" "Jersey" "Liechtenstein" ...
 $ ISO3                                : chr [1:228] "FLK" "SHN" "JEY" "LIE" ...
 $ WHO_REGION                          : chr [1:228] "AMRO" "AFRO" "EURO" "OTHER" ...
 $ DATA_SOURCE                         : chr [1:228] "OWID" "OWID" "OWID" "OWID" ...
 $ DATE_UPDATED                        : Date[1:228], format: "2021-04-14" "2021-05-05" ...
 $ TOTAL_VACCINATIONS                  : num [1:228] 4407 7892 162928 48245 102548 ...
 $ PERSONS_VACCINATED_1PLUS_DOSE       : num [1:228] 2632 4361 78261 24829 NA ...
 $ TOTAL_VACCINATIONS_PER100           : num [1:228] 127 130 151 125 159 ...
 $ PERSONS_VACCINATED_1PLUS_DOSE_PER100: num [1:228] 75.6 71.8 72.6 64.1 NA ...
 $ PERSONS_FULLY_VACCINATED            : num [1:228] 1775 3531 74327 24124 NA ...
 $ PERSONS_FULLY_VACCINATED_PER100     : num [1:228] 51 58.2 69 62.3 NA ...
 $ VACCINES_USED                       : chr [1:228] "AstraZeneca - AZD1222" "AstraZeneca - AZD1222" "Moderna - mRNA-1273, AstraZeneca - AZD1222, Pfizer BioNTech - Comirnaty" "Moderna - mRNA-1273, Pfizer BioNTech - Comirnaty" ...
 $ FIRST_VACCINE_DATE                  : Date[1:228], format: NA NA ...
 $ NUMBER_VACCINES_TYPES_USED          : num [1:228] 1 1 3 2 3 3 1 1 2 10 ...
 - attr(*, "spec")=
  .. cols(
  ..   COUNTRY = col_character(),
  ..   ISO3 = col_character(),
  ..   WHO_REGION = col_character(),
  ..   DATA_SOURCE = col_character(),
  ..   DATE_UPDATED = col_date(format = ""),
  ..   TOTAL_VACCINATIONS = col_double(),
  ..   PERSONS_VACCINATED_1PLUS_DOSE = col_double(),
  ..   TOTAL_VACCINATIONS_PER100 = col_double(),
  ..   PERSONS_VACCINATED_1PLUS_DOSE_PER100 = col_double(),
  ..   PERSONS_FULLY_VACCINATED = col_double(),
  ..   PERSONS_FULLY_VACCINATED_PER100 = col_double(),
  ..   VACCINES_USED = col_character(),
  ..   FIRST_VACCINE_DATE = col_date(format = ""),
  ..   NUMBER_VACCINES_TYPES_USED = col_double()
  .. )
 - attr(*, "problems")=<externalptr>

In [22]:
#selecting the columns and renaming them
vaccines_df <- vaccines_df %>% 
    select(ISO3, COUNTRY, TOTAL_VACCINATIONS,
           PERSONS_VACCINATED_1PLUS_DOSE,
           PERSONS_FULLY_VACCINATED, 
           TOTAL_VACCINATIONS_PER100,
           FIRST_VACCINE_DATE,
           DATE_UPDATED) %>%
    rename(country_code = ISO3,
           country_name = COUNTRY,
           total_vaccinations = TOTAL_VACCINATIONS,
           vaccinated_1dose = PERSONS_VACCINATED_1PLUS_DOSE,
           fully_vacccinated = PERSONS_FULLY_VACCINATED,
           total_vaccinations_per100 = TOTAL_VACCINATIONS_PER100,
           first_vaccine_date = FIRST_VACCINE_DATE,
           last_updated_date = DATE_UPDATED)

In [23]:
vaccines_df

    country_code country_name                     total_vaccinations
1   FLK          Falkland Islands (Malvinas)          4407
2   SHN          Saint Helena                         7892
3   JEY          Jersey                             162928
4   LIE          Liechtenstein                       48245
5   GGY          Guernsey                           102548
6   IMN          Isle of Man                        131628
7   GIB          Gibraltar                           84477
8   GRL          Greenland                           77006
9   FRO          Faroe Islands                       76516
10  PHL          Philippines                      51482063
11  NGA          Nigeria                           8402127
12  OMN          Oman                              5271912
13  CUW          Cura\347ao                            191202
14  NIU          Niue                                 2352
15  VNM          Viet Nam                         59003239
16  SYC          Seychelles                         165206
17  THA          Thailand                         63727301
18  PAN          Panama                            5741258
19  FJI          Fiji                              1136909
20  CAN          Canada                           57669374
21  BLZ          Belize                             373000
22  XBA          Sint Eustatius                       2931
23  XAA          Bonaire                             31112
24  COD          Democratic Republic of the Congo   147734
25  MSR          Montserrat                           2911
26  MLI          Mali                               429914
27  MWI          Malawi                            1237220
28  BTN          Bhutan                            1103506
29  MDG          Madagascar                         502053
30  JAM          Jamaica                            887675
... ...          ...                              ...
199 AZE          Azerbaijan                         8646806
200 DNK          Denmark                            8812768
201 LTU          Lithuania                          3258830
202 DEU          Germany                          108685938
203 UKR          Ukraine                           14425128
204 ALB          Albania                            1835736
205 MCO          Monaco                               49980
206 AND          Andorra                             102692
207 SRB          Serbia                             6043997
208 TKM          Turkmenistan                       7580976
209 RUS          Russian Federation                94491689
210 ARM          Armenia                             620698
211 SWE          Sweden                            13963719
212 TJK          Tajikistan                         4631515
213 LUX          Luxembourg                          776757
214 NOR          Norway                             7897552
215 ISR          Israel                            11919798
216 BGR          Bulgaria                           2621336
217 MNE          Montenegro                          456156
218 ROU          Romania                           10704774
219 CYP          Cyprus                             1163412
220 KGZ          Kyrgyzstan                         1579659
221 GRC          Greece                            12333381
222 ESP          Spain                             70390395
223 GBR          The United Kingdom                94800164
224 SVK          Slovakia                           4761628
225 NLD          Netherlands                       22561963
226 AUT          Austria                           11020915
227 MDA          Republic of Moldova                1458501
228 MKD          North Macedonia                    1559974
    vaccinated_1dose fully_vacccinated total_vaccinations_per100
1       2632             1775          126.529
2       4361             3531          129.995
3      78261            74327          151.145
4      24829            24124          124.513
5         NA               NA          159.068
6      67353            64275          154.798
7      40173            39796          250.741
8      40104            36902          135.641
9      39114            37402          156.587
10  31125861         23981240           46.981
11   5526303          2875824            4.076
12   2962504          2309408          103.237
13     99629            91573          116.521
14      1202             1150          145.365
15  41811429         17191810           60.616
16     81021            76188          167.983
17  37684728         26042573           91.300
18   3029679          2649359          133.061
19    619734           517175          126.824
20  29460580         27792564          152.798
21    221830           186230           93.806
22      1492             1439           93.374
23     16591            14521          148.754
24    109579            38155            0.165
25      1502             1409           58.232
26    319087           256382            2.123
27    909871           536108            6.467
28    585993           517513          143.014
29    198863           303190            1.813
30    575243           399254           29.977
... ...              ...               ...
199  4782922          3863884           85.3
200  4464715          4348053          151.4
201  1779962          1474770          116.6
202 57256654         51429284          130.7
203  7995142          6429986           33.0
204   977034           858702           63.8
205    26672            23308          127.4
206    54383            48309          132.9
207  3085630          2958367           87.3
208  4374694          3206282          125.7
209 49463056         45028077           64.7
210   434617           186081           20.9
211  7193876          6769843          135.2
212  2592147          2039368           48.6
213   413682           363075          124.1
214  4191824          3705728          147.1
215  6209522          5710276          137.7
216  1450139          1171197           37.7
217   247252           208904           72.6
218  6021494          4683280           55.4
219   600623           562789          131.0
220   895923           683736           24.2
221  6496708          5836673          115.1
222 37849576         32540819          148.7
223 49422753         45261635          139.6
224  2458720          2302908           87.2
225 12251325         10310638          129.6
226  5817157          5203758          123.8
227   862032           596469           36.2
228   798946           761028           74.9
    first_vaccine_date last_updated_date
1   <NA>               2021-04-14
2   <NA>               2021-05-05
3   <NA>               2021-10-18
4   <NA>               2021-10-21
5   <NA>               2021-10-18
6   <NA>               2021-10-21
7   <NA>               2021-10-20
8   <NA>               2021-10-21
9   <NA>               2021-10-21
10  2021-03-01         2021-10-14
11  2021-03-05         2021-10-23
12  2020-12-29         2021-10-10
13  2021-02-24         2021-10-22
14  2021-06-08         2021-08-02
15  2021-03-08         2021-10-14
16  2021-01-10         2021-10-25
17  2021-02-28         2021-10-17
18  2021-01-20         2021-10-22
19  2021-03-07         2021-10-15
20  2020-12-14         2021-10-22
21  2021-03-01         2021-10-22
22  <NA>               2021-10-22
23  <NA>               2021-10-22
24  2021-04-19         2021-10-25
25  2021-02-08         2021-10-22
26  2021-03-31         2021-10-22
27  2021-03-11         2021-10-24
28  2021-03-27         2021-10-18
29  2021-05-10         2021-10-20
30  2021-03-10         2021-10-22
... ...                ...
199 2021-01-20         2021-10-10
200 2020-12-16         2021-10-17
201 2020-12-23         2021-10-17
202 2020-12-23         2021-10-17
203 2021-02-24         2021-10-17
204 2021-01-13         2021-10-17
205 2021-06-30         2021-09-16
206 2021-01-20         2021-10-03
207 2020-12-23         2021-10-03
208 2021-02-24         2021-08-29
209 <NA>               2021-10-13
210 2021-06-16         2021-10-17
211 2020-12-23         2021-10-17
212 2021-03-24         2021-10-17
213 2020-12-30         2021-10-17
214 2020-12-23         2021-10-17
215 2020-12-16         2021-10-17
216 2020-12-30         2021-10-17
217 2021-02-24         2021-10-17
218 2021-01-27         2021-10-17
219 2020-12-23         2021-10-17
220 2021-03-31         2021-10-17
221 2020-12-23         2021-10-17
222 2020-12-30         2021-10-17
223 2020-12-21         2021-10-18
224 2021-01-06         2021-10-17
225 2021-01-06         2021-10-17
226 2020-12-30         2021-10-17
227 2021-03-03         2021-10-17
228 2021-02-17         2021-10-17

In [24]:
#combine the data frame by country code and name
covid_df <- left_join(cases_df, vaccines_df, by=c('country_code', 'country_name'))

In [25]:
covid_df

    country_code country_name                                   total_cases
1   USA          United States of America                       45258928
2   IND          India                                          34215653
3   BRA          Brazil                                         21735560
4   GBR          The United Kingdom                              8853231
5   RUS          Russian Federation                              8352601
6   TUR          Turkey                                          7909111
7   FRA          France                                          6911563
8   IRN          Iran (Islamic Republic of)                      5877456
9   ARG          Argentina                                       5281585
10  ESP          Spain                                           5004144
11  COL          Colombia                                        4992586
12  ITA          Italy                                           4747773
13  DEU          Germany                                         4506415
14  IDN          Indonesia                                       4241809
15  MEX          Mexico                                          3784448
16  POL          Poland                                          2990509
17  ZAF          South Africa                                    2920109
18  UKR          Ukraine                                         2825733
19  PHL          Philippines                                     2765672
20  MYS          Malaysia                                        2442224
21  PER          Peru                                            2196259
22  NLD          Netherlands                                     2093606
23  IRQ          Iraq                                            2049240
24  THA          Thailand                                        1875315
25  CZE          Czechia                                         1741859
26  JPN          Japan                                           1717367
27  CAN          Canada                                          1702587
28  CHL          Chile                                           1684608
29  ROU          Romania                                         1602830
30  BGD          Bangladesh                                      1568563
... ...          ...                                            ...
202 GGY          Guernsey                                       2055
203 FRO          Faroe Islands                                  1778
204 BLM          Saint Barth\351lemy                               1659
205 CYM          Cayman Islands                                 1279
206 AIA          Anguilla                                        859
207 GRL          Greenland                                       772
208 WLF          Wallis and Futuna                               454
209 MNP          Northern Mariana Islands (Commonwealth of the)  291
210 FLK          Falkland Islands (Malvinas)                      69
211 MSR          Montserrat                                       41
212 SPM          Saint Pierre and Miquelon                        32
213 VAT          Holy See                                         26
214 SLB          Solomon Islands                                  20
215 PLW          Palau                                             8
216 VUT          Vanuatu                                           5
217 ASM          American Samoa                                    4
218 MHL          Marshall Islands                                  4
219 WSM          Samoa                                             1
220 COK          Cook Islands                                      0
221 PRK          Democratic People's Republic of Korea             0
222 KIR          Kiribati                                          0
223 FSM          Micronesia (Federated States of)                  0
224 NRU          Nauru                                             0
225 NIU          Niue                                              0
226 PCN          Pitcairn Islands                                  0
227 SHN          Saint Helena                                      0
228 TKL          Tokelau                                           0
229 TON          Tonga                                             0
230 TKM          Turkmenistan                                      0
231 TUV          Tuvalu                                            0
    total_deaths region                total_vaccinations vaccinated_1dose
1   732512       Americas              423902300          237522038
2   455653       South-East Asia       986769411          699116940
3   605804       Americas              254011119          153755552
4   139834       Europe                 94800164           49422753
5   233898       Europe                 94491689           49463056
6    69559       Europe                112360409           54497626
7   115168       Europe                 95249797           50862471
8   125519       Eastern Mediterranean  72643522           48474187
9   115851       Americas               57450735           32400490
10   87238       Europe                 70390395           37849576
11  127099       Americas               45200937           28866402
12  131904       Europe                 86324861           45974785
13   95359       Europe                108685938           57256654
14  143299       South-East Asia       173949386          109584683
15  286496       Americas              113471215           69612911
16   76672       Europe                 38252622           20472026
17   88987       Africa                 21321996           14759385
18   65628       Europe                 14425128            7995142
19   42077       Western Pacific        51482063           31125861
20   28576       Western Pacific        45900724           24663184
21  200083       Americas               32957509           18256677
22   18340       Europe                 22561963           12251325
23   23024       Eastern Mediterranean   8972041            5621027
24   18922       South-East Asia        63727301           37684728
25   30667       Europe                 11907902            6128231
26   18221       Western Pacific       178255509           94599325
27   28805       Americas               57669374           29460580
28   37691       Americas               34970187           16265400
29   46015       Europe                 10704774            6021494
30   27841       South-East Asia        58801055           39168948
... ...          ...                   ...                ...
202 22           Europe                 102548                 NA
203  2           Europe                  76516              39114
204  4           Americas                   NA                 NA
205  2           Americas               111027              55991
206  1           Americas                18705               9548
207  0           Europe                  77006              40104
208  7           Western Pacific         11102               5781
209  3           Western Pacific         70330              35996
210  0           Americas                 4407               2632
211  1           Americas                 2911               1502
212  0           Americas                   NA                 NA
213  0           Europe                     NA                 NA
214  0           Western Pacific        152832             121778
215  0           Western Pacific         30940              17768
216  0           Western Pacific         14955               8880
217  0           Western Pacific         63694              34565
218  0           Western Pacific         40954              23021
219  0           Western Pacific        188664             115354
220  0           Western Pacific         23489              12297
221  0           South-East Asia            NA                 NA
222  0           Western Pacific         65279              54026
223  0           Western Pacific         73747              45439
224  0           Western Pacific         14790               7612
225  0           Western Pacific          2352               1202
226  0           Western Pacific            74                 37
227  0           Africa                   7892               4361
228  0           Western Pacific          1936                968
229  0           Western Pacific         84506              51048
230  0           Europe                7580976            4374694
231  0           Western Pacific         10861               6209
    fully_vacccinated total_vaccinations_per100 first_vaccine_date
1   205645913         128.066                   2020-12-14
2   287652471          71.505                   2021-01-16
3   109815846         119.501                   2021-01-17
4    45261635         139.600                   2020-12-21
5    45028077          64.700                   <NA>
6    46903485         133.200                   <NA>
7    44387326         141.500                   2020-12-30
8    24169335          86.488                   2021-02-09
9    25243273         127.115                   2020-12-29
10   32540819         148.700                   2020-12-30
11   23916914          88.833                   2021-02-17
12   40347396         144.700                   2020-12-23
13   51429284         130.700                   2020-12-23
14   64364703          63.596                   2021-01-13
15   60377350          88.008                   2020-12-24
16   17622052         100.800                   2020-12-23
17   11560623          35.951                   2021-02-17
18    6429986          33.000                   2021-02-24
19   23981240          46.981                   2021-03-01
20   21907522         141.818                   2021-02-24
21   14565468          99.956                   2021-02-09
22   10310638         129.600                   2021-01-06
23    3351014          22.306                   2021-03-02
24   26042573          91.300                   2021-02-28
25    5779671         111.400                   2020-12-23
26   83656184         140.940                   2021-02-17
27   27792564         152.798                   2020-12-14
28   15123888         182.935                   2020-12-21
29    4683280          55.400                   2021-01-27
30   19632107          35.704                   2021-01-27
... ...               ...                       ...
202      NA           159.068                   <NA>
203   37402           156.587                   <NA>
204      NA                NA                   <NA>
205   53684           168.939                   2021-01-15
206    9157           124.683                   2021-02-05
207   36902           135.641                   <NA>
208    5321            98.720                   2021-03-19
209   35155           122.192                   2020-12-19
210    1775           126.529                   <NA>
211    1409            58.232                   2021-02-08
212      NA                NA                   <NA>
213      NA                NA                   <NA>
214   31054            22.250                   2021-03-23
215   15505           171.015                   2021-01-03
216    6076             4.869                   2021-06-02
217   29675           115.394                   2020-12-21
218   20058            69.186                   2020-12-29
219   73310            95.086                   2021-04-18
220   11192           133.734                   2021-05-17
221      NA                NA                   <NA>
222   11253            54.650                   2021-05-26
223   39970            64.115                   2021-01-13
224    7178           136.515                   2021-04-09
225    1150           145.365                   2021-06-08
226      37           148.000                   2021-05-17
227    3531           129.995                   <NA>
228     968           143.407                   2021-07-20
229   33458            79.953                   2021-04-14
230 3206282           125.700                   2021-02-24
231    4652            92.105                   2021-04-13
    last_updated_date
1   2021-10-22
2   2021-10-19
3   2021-10-22
4   2021-10-18
5   2021-10-13
6   2021-10-13
7   2021-10-17
8   2021-10-17
9   2021-10-22
10  2021-10-17
11  2021-10-22
12  2021-10-17
13  2021-10-17
14  2021-10-19
15  2021-10-22
16  2021-10-17
17  2021-10-24
18  2021-10-17
19  2021-10-14
20  2021-10-15
21  2021-10-22
22  2021-10-17
23  2021-10-24
24  2021-10-17
25  2021-10-17
26  2021-10-14
27  2021-10-22
28  2021-10-22
29  2021-10-17
30  2021-10-19
... ...
202 2021-10-18
203 2021-10-21
204 <NA>
205 2021-10-22
206 2021-10-22
207 2021-10-21
208 2021-10-15
209 2021-10-15
210 2021-04-14
211 2021-10-22
212 <NA>
213 <NA>
214 2021-10-15
215 2021-10-14
216 2021-10-17
217 2021-10-14
218 2021-10-14
219 2021-10-13
220 2021-10-11
221 <NA>
222 2021-10-15
223 2021-10-14
224 2021-08-20
225 2021-08-02
226 2021-09-16
227 2021-05-05
228 2021-09-28
229 2021-10-18
230 2021-08-29
231 2021-09-10

In [26]:
#collecting raw data using API 
url <- GET("https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/date-range/{start-date}/{end-date}")

In [27]:
#search key is by latest date
stringency_df <- get_json_time(from = "2021-10-17") %>% get_data_time()

In [28]:
str(stringency_df)

tibble [1,418 x 9] (S3: tbl_df/tbl/data.frame)
 $ date_value            : Date[1:1418], format: "2021-10-17" "2021-10-17" ...
 $ country_code          : chr [1:1418] "NGA" "UKR" "GRC" "USA" ...
 $ country_name          : chr [1:1418] "Nigeria" "Ukraine" "Greece" "United States" ...
 $ confirmed             : int [1:1418] 209298 2757328 693886 44934357 460322 16621 308136 13396 12455 805037 ...
 $ deaths                : int [1:1418] 2837 64603 15375 724728 16209 129 4638 179 33 11284 ...
 $ stringency_actual     : num [1:1418] 50.9 58.3 71.8 56 38.9 ...
 $ stringency            : num [1:1418] 50.9 58.3 71.8 56 38.9 ...
 $ stringency_legacy     : num [1:1418] 63.8 71 77.4 60.2 47.1 ...
 $ stringency_legacy_disp: num [1:1418] 63.8 71 77.4 60.2 47.1 ...

In [29]:
#selecting the columns
stringency_df<- stringency_df %>% 
    select(country_code, stringency)

In [30]:
head(stringency_df)

  country_code stringency
1 NGA          50.93
2 UKR          58.33
3 GRC          71.76
4 USA          56.02
5 PRY          38.89
6 MUS          32.41

In [31]:
#combine the two dataframes by country code
covid_str_df <- left_join(covid_df, stringency_df, by=c('country_code'))

In [32]:
#removes the duplicate rows
covid_str_df <- covid_str_df[!duplicated(covid_str_df$country_code),]

In [34]:
write.csv(covid_str_df, "Covid_Data_New.csv")